top_srcdir   = /home/james/abs/extra/apache/src/httpd-2.4.3
top_builddir = /home/james/abs/extra/apache/src/httpd-2.4.3
srcdir       = /home/james/abs/extra/apache/src/httpd-2.4.3/modules
builddir     = /home/james/abs/extra/apache/src/httpd-2.4.3/modules
VPATH        = /home/james/abs/extra/apache/src/httpd-2.4.3/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

