top_srcdir   = /home/james/abs/extra/apache/src/httpd-2.4.3
top_builddir = /home/james/abs/extra/apache/src/httpd-2.4.3
srcdir       = /home/james/abs/extra/apache/src/httpd-2.4.3/modules/cache
builddir     = /home/james/abs/extra/apache/src/httpd-2.4.3/modules/cache
VPATH        = /home/james/abs/extra/apache/src/httpd-2.4.3/modules/cache

include $(top_srcdir)/build/special.mk

