top_srcdir   = /home/james/abs/extra/apache/src/httpd-2.4.3
top_builddir = /home/james/abs/extra/apache/src/httpd-2.4.3
srcdir       = /home/james/abs/extra/apache/src/httpd-2.4.3/modules/echo
builddir     = /home/james/abs/extra/apache/src/httpd-2.4.3/modules/echo
VPATH        = /home/james/abs/extra/apache/src/httpd-2.4.3/modules/echo

include $(top_srcdir)/build/special.mk

