top_srcdir   = /home/james/abs/extra/apache/src/httpd-2.4.3
top_builddir = /home/james/abs/extra/apache/src/httpd-2.4.3
srcdir       = /home/james/abs/extra/apache/src/httpd-2.4.3/server/mpm/prefork
builddir     = /home/james/abs/extra/apache/src/httpd-2.4.3/server/mpm/prefork
VPATH        = /home/james/abs/extra/apache/src/httpd-2.4.3/server/mpm/prefork
include $(top_srcdir)/build/special.mk
