top_srcdir   = /home/james/abs/extra/apache/src/httpd-2.4.3
top_builddir = /home/james/abs/extra/apache/src/httpd-2.4.3
srcdir       = /home/james/abs/extra/apache/src/httpd-2.4.3/modules/aaa
builddir     = /home/james/abs/extra/apache/src/httpd-2.4.3/modules/aaa
VPATH        = /home/james/abs/extra/apache/src/httpd-2.4.3/modules/aaa

include $(top_srcdir)/build/special.mk

