top_srcdir   = /home/james/abs/extra/apache/src/httpd-2.4.3
top_builddir = /home/james/abs/extra/apache/src/httpd-2.4.3
srcdir       = /home/james/abs/extra/apache/src/httpd-2.4.3/server/mpm/worker
builddir     = /home/james/abs/extra/apache/src/httpd-2.4.3/server/mpm/worker
VPATH        = /home/james/abs/extra/apache/src/httpd-2.4.3/server/mpm/worker

include $(top_srcdir)/build/special.mk
