top_srcdir   = /home/james/abs/extra/apache/src/httpd-2.4.3
top_builddir = /home/james/abs/extra/apache/src/httpd-2.4.3
srcdir       = /home/james/abs/extra/apache/src/httpd-2.4.3/modules/test
builddir     = /home/james/abs/extra/apache/src/httpd-2.4.3/modules/test
VPATH        = /home/james/abs/extra/apache/src/httpd-2.4.3/modules/test
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
