top_srcdir   = /home/james/abs/extra/apache/src/httpd-2.4.3
top_builddir = /home/james/abs/extra/apache/src/httpd-2.4.3
srcdir       = /home/james/abs/extra/apache/src/httpd-2.4.3/modules/metadata
builddir     = /home/james/abs/extra/apache/src/httpd-2.4.3/modules/metadata
VPATH        = /home/james/abs/extra/apache/src/httpd-2.4.3/modules/metadata

include $(top_srcdir)/build/special.mk

