top_srcdir   = /home/james/abs/extra/apache/src/httpd-2.4.3
top_builddir = /home/james/abs/extra/apache/src/httpd-2.4.3
srcdir       = /home/james/abs/extra/apache/src/httpd-2.4.3/os
builddir     = /home/james/abs/extra/apache/src/httpd-2.4.3/os
VPATH        = /home/james/abs/extra/apache/src/httpd-2.4.3/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
